### ISSUE TITLE
a missing detail for Windows ?

### ISSUE THREAD

**Issue by stonebig** [mikeckennedy/pyscript-pwa-example#1]
I can install the web app to Chrome and Edge.
But in each case, when I launch the webapp from the desktop,  it starts with a blue background screen 

![image](https://user-images.githubusercontent.com/4312421/170822290-d55fa48c-3c88-4182-ac51-3765ae62ae67.png)

 then fails with this

![image](https://user-images.githubusercontent.com/4312421/170822287-cbc29b28-9b6e-41e2-9b79-441fe9c6dbdc.png)

what did I miss ?

**Comment by stonebig** [comment]
by the way, you may precise it shall work on Chrome and Edge (and more ?)

**Comment by stonebig** [comment]
`keep the app running for the web weather API`

**Comment by mikeckennedy** [comment]
Hey. It should work if you have the python Flask app running which it needs to load the page and to get the API calls to work.

**Comment by stonebig** [comment]
yes yes, it works now... interesting. If we could read files from a local directory, or a sql server database, it would become an interesting alternative to many, many things.

**Comment by mikeckennedy** [comment]
> "If we could read files from a local directory, or a sql server database, it would become an interesting alternative to many, many things"

@stonebig Indeed! I imagine someone (hopefully not me ;) ) will create a Python DB layer that could use the built-in web browser's LocalDB. Wrap it with some sort of simple ORM based on Pydantic and you'd be in really good shape. Sync it back with an API on the server if needed.
